1. 아직 모르는 물리 공식 써보기 (칼럼 생성)
2. 도비님 & 오버샘플링 사용해서 데이터 증강하기 (데이터 세로로 길어짐)

## 신호벡터크기

에너지로 변환하는 공식: $ SVM = sqrt (x² + y² + z²) $

"Signal Vector Magnitude는 중력에 대한 3축 가속도 신호의 방향 성분을 상쇄하고 신호 벡터의 크기를 얻어내는 방법이다. 이는 스마트폰과 같이 휴대방법에 따라 뒤섞이는 센서의 축 방향 손실과 무관하게 패턴 정보를 획득 가능한 방법 중 하나이다."

## 고속 푸리에 변환

신호를 분석할 때 시간 영역으로 표현된 신호를 주파수 영역으로 변환, 다른 관점에서 분석할 수 있도록 함.

https://m.blog.naver.com/PostView.nhn?blogId=samsjang&logNo=220565430664&proxyReferer=https:%2F%2Fwww.google.com%2F

In [13]:
import pandas as pd
import numpy as np

In [31]:
train_feature = pd.read_csv('../prj_running_machine/data/train_features.csv')
train_label = pd.read_csv('../prj_running_machine/data/train_labels.csv')
test_feature = pd.read_csv('../prj_running_machine/data/test_features.csv')
sample = pd.read_csv('../prj_running_machine/data/sample_submission.csv')

In [32]:
# 신호벡터크기(에너지값) 칼럼 생성

train_feature['acc_energy'] = \
(train_feature['acc_x']**2 + train_feature['acc_y']**2 + train_feature['acc_z']**2)**(1/3)
test_feature['acc_energy'] = \
(test_feature['acc_x']**2 + test_feature['acc_y']**2 + test_feature['acc_z']**2)**(1/3)

train_feature['gy_energy'] =\
(train_feature['gy_x']**2 + train_feature['gy_y']**2 + train_feature['gy_z']**2)**(1/3)
test_feature['gy_energy'] = \
(test_feature['gy_x']**2 + test_feature['gy_y']**2 + test_feature['gy_z']**2)**(1/3)


train_feature['gy_acc_energy'] = \
((train_feature['gy_x'] - train_feature['acc_x'])**2 
 + (train_feature['gy_y'] - train_feature['acc_y'])**2 
 + (train_feature['gy_z'] - train_feature['acc_z']**2))**(1/3)

test_feature['gy_acc_energy'] = \
((test_feature['gy_x'] - test_feature['acc_x'])**2 
 + (test_feature['gy_y'] - test_feature['acc_y'])**2 
 + (test_feature['gy_z'] - test_feature['acc_z']**2))**(1/3)

In [33]:
train_feature

,id,time,acc_x,acc_y,acc_z,gy_x,gy_y,gy_z,acc_energy,gy_energy,gy_acc_energy
0,0,0,1.206087,-0.179371,-0.148447,-0.591608,-30.549010,-31.676112,1.146962,12.465436,9.632846
1,0,1,1.287696,-0.198974,-0.182444,0.303100,-39.139103,-24.927216,1.200703,12.913284,11.427630
2,0,2,1.304609,-0.195114,-0.253382,-3.617278,-44.122565,-25.019629,1.217403,13.725729,12.447808
3,0,3,1.293095,-0.230366,-0.215210,2.712986,-53.597843,-27.454013,1.209981,15.374021,14.132423
4,0,4,1.300887,-0.187757,-0.222523,4.286707,-57.906561,-27.961234,1.211254,16.074363,14.906627
...,...,...,...,...,...,...,...,...,...,...,...
1874995,3124,595,-0.712530,-0.658357,0.293707,-29.367857,-104.013664,-76.290437,1.009050,25.963234,22.523972
1874996,3124,596,-0.683037,-0.658466,0.329223,-30.149089,-101.796809,-76.625087,1.002827,25.784692,22.253594
1874997,3124,597,-0.664730,-0.666625,0.364114,-27.873095,-98.776072,-79.365125,1.006239,25.628060,21.747993
1874998,3124,598,-0.630534,-0.682565,0.373696,-23.636550,-99.139495,-80.259478,1.001038,25.626266,21.646303
1874999,3124,599,-0.578351,-0.700235,0.384390,-17.917626,-100.181873,-80.676229,0.990773,25.645131,21.627633

In [36]:
print(train_feature.shape)
print(x_train.shape)
x_train = x_train.reshape(-1, 9)
x_train

(1875000, 11)
(1875000, 9)

array([[ 1.2060866 ,  1.2876965 ,  1.3046092 , ...,  1.2814054 ,
         1.2422733 ,  1.1988714 ],
       [ 1.1136771 ,  1.1922414 ,  1.2300943 , ...,  0.9938655 ,
         0.95658845,  0.9773573 ],
       [ 0.9979869 ,  0.91410583,  0.8517348 , ...,  0.7211082 ,
         0.7024572 ,  0.6990579 ],
       ...,
       [13.892408  , 15.634141  , 16.461895  , ..., 18.859598  ,
        19.40057   , 19.770105  ],
       [19.988838  , 20.295565  , 20.639563  , ..., 21.563732  ,
        21.613096  , 21.697693  ],
       [22.048077  , 22.258186  , 22.222298  , ..., 21.747993  ,
        21.646303  , 21.627632  ]], dtype=float32)

In [40]:
df = pd.DataFrame(x_train, columns=['acc_x','acc_y','acc_z','gy_x','gy_y','gy_z','gy_acc_energy','acc_energy','gy_energy'])
df

,acc_x,acc_y,acc_z,gy_x,gy_y,gy_z,gy_acc_energy,acc_energy,gy_energy
0,1.206087,1.287696,1.304609,1.293095,1.300887,1.289304,1.281405,1.242273,1.198871
1,1.113677,1.192241,1.230094,1.175210,1.170251,1.075277,0.993865,0.956588,0.977357
2,0.997987,0.914106,0.851735,0.790079,0.759773,0.736777,0.721108,0.702457,0.699058
3,0.623462,0.654510,0.682234,0.712764,0.729719,0.761901,0.676890,0.633556,0.628711
4,0.687481,0.689470,0.616131,0.659277,0.711882,0.696517,0.776035,0.855469,0.730303
...,...,...,...,...,...,...,...,...,...
1874995,14.326978,12.751825,11.609216,10.637752,10.214480,10.106851,9.210572,7.858559,6.649084
1874996,5.431305,3.566184,3.037933,6.441206,8.051457,9.303647,10.671305,11.878014,12.461176
1874997,13.892408,15.634141,16.461895,17.003391,17.653616,18.233694,18.859598,19.400570,19.770105
1874998,19.988838,20.295565,20.639563,20.918701,21.058018,21.280809,21.563732,21.613096,21.697693
1874999,22.048077,22.258186,22.222298,22.319174,22.523972,22.253593,21.747993,21.646303,21.627632

In [14]:
# 도비 증강코드

x_train = []

for uid in train_feature['id'].unique():
    temp = np.array(train_feature[train_feature['id'] == uid].iloc[:,2:], np.float32).T
    x_train.append(temp)

x_train = np.array(x_train, np.float32)
x_train = x_train[:,:,:,np.newaxis]

x_test = []

for uid in test_feature['id'].unique():
    temp = np.array(test_feature[test_feature['id'] == uid].iloc[:,2:], np.float32).T
    x_test.append(temp)

x_test = np.array(x_test, np.float32)
x_test = x_test[:,:,:,np.newaxis]